<h1 align='center'>Assignment No 21</h1>

Q1 Write a function that takes a list and a number as arguments. Add the number to the end of<br>
the list, then remove the first element of the list. The function should then <br>return the updated<br>
list.<br>
Examples<br>
next_in_line([5, 6, 7, 8, 9], 1) ➞ [6, 7, 8, 9, 1]<br>
next_in_line([7, 6, 3, 23, 17], 10) ➞ [6, 3, 23, 17, 10]<br>
next_in_line([1, 10, 20, 42 ], 6) ➞ [10, 20, 42, 6]<br>
next_in_line([], 6) ➞ &quot;No list has been selected&quot;

In [ ]:
def next_in_line(ls,ele):
  new_ls = []
  if len(ls)>0:
    for i in range(1,len(ls)):
      new_ls.append(ls[i])
    new_ls.append(ele)
    return new_ls
  else:
    return "No list has been selected"

print(next_in_line([5, 6, 7, 8, 9], 1))
print(next_in_line([7, 6, 3, 23, 17], 10))
print(next_in_line([1, 10, 20, 42 ], 6))
print(next_in_line([], 6))

[6, 7, 8, 9, 1]
[6, 3, 23, 17, 10]
[10, 20, 42, 6]
No list has been selected

Q2 Create the function that takes a list of dictionaries and returns the sum of people&#39;s budgets.<br>
Examples<br>
get_budgets([
{ &quot;name&quot;: &quot;John&quot;, &quot;age&quot;: 21, &quot;budget&quot;: 23000 },
{ &quot;name&quot;: &quot;Steve&quot;, &quot;age&quot;: 32, &quot;budget&quot;: 40000 },
{ &quot;name&quot;: &quot;Martin&quot;, &quot;age&quot;: 16, &quot;budget&quot;: 2700 }
]) ➞ 65700<br>
get_budgets([
{ &quot;name&quot;: &quot;John&quot;, &quot;age&quot;: 21, &quot;budget&quot;: 29000 },
{ &quot;name&quot;: &quot;Steve&quot;, &quot;age&quot;: 32, &quot;budget&quot;: 32000 },
{ &quot;name&quot;: &quot;Martin&quot;, &quot;age&quot;: 16, &quot;budget&quot;: 1600 }
]) ➞ 62600

In [ ]:
def get_budgets(ls):
  sum = 0
  for i in ls:
    sum = sum + i['budget']
  return sum

print(get_budgets([ { "name": "John", "age": 21, "budget": 23000 }, { "name": "Steve", "age": 32, "budget": 40000 }, { "name": "Martin", "age": 16, "budget": 2700 } ]))
get_budgets([ { "name": "John", "age": 21, "budget": 29000 }, { "name": "Steve", "age": 32, "budget": 32000 }, { "name": "Martin", "age": 16, "budget": 1600 } ])

65700

62600

Q3 Create a function that takes a string and returns a string with its letters in alphabetical order.<br>
Examples<br>
alphabet_soup(&quot;hello&quot;) ➞ &quot;ehllo&quot;<br>
alphabet_soup(&quot;edabit&quot;) ➞ &quot;abdeit&quot;<br>
alphabet_soup(&quot;hacker&quot;) ➞ &quot;acehkr&quot;<br>
alphabet_soup(&quot;geek&quot;) ➞ &quot;eegk&quot;<br>
alphabet_soup(&quot;javascript&quot;) ➞ &quot;aacijprstv&quot;

In [ ]:
def alphabet_soup(s):
  return "".join(sorted(s))

print(alphabet_soup("hello"))
print(alphabet_soup("edabit"))
print(alphabet_soup("hacker"))
print(alphabet_soup("geek"))
print(alphabet_soup("javascript"))

ehllo
abdeit
acehkr
eegk
aacijprstv

Q4 Suppose that you invest $10,000 for 10 years at an interest rate of 6% compounded monthly.<br>
What will be the value of your investment at the end of the 10 year period?
Create a function that accepts the principal p, the term in years t, the interest rate r, and the<br>
number of compounding periods per year n. The function returns the value at the end of term<br>
rounded to the nearest cent.<br>
For the example above:<br>
compound_interest(10000, 10, 0.06, 12) ➞ 18193.97<br>
Note that the interest rate is given as a decimal and n=12 because with monthly compounding<br>
there are 12 periods per year. Compounding can also be done annually, quarterly, weekly, or<br>
daily.
Examples<br>
compound_interest(100, 1, 0.05, 1) ➞ 105.0<br>
compound_interest(3500, 15, 0.1, 4) ➞ 15399.26<br>
compound_interest(100000, 20, 0.15, 365) ➞ 2007316.26<br>

In [2]:
def compound_interest(p,t,r,n):
  a = p*(1+r/n)**(n*t)
  return round(a,2)

print(compound_interest(100, 1, 0.05, 1))
print(compound_interest(3500, 15, 0.1, 4))
print(compound_interest(100000, 20, 0.15, 365))

105.0
15399.26
2007316.26

Q5  Write a function that takes a list of elements and returns only the integers.
Examples<br>
return_only_integer([9, 2, &quot;space&quot;, &quot;car&quot;, &quot;lion&quot;, 16]) ➞ [9, 2, 16]<br>
return_only_integer([&quot;hello&quot;, 81, &quot;basketball&quot;, 123, &quot;fox&quot;]) ➞ [81, 123]<br>
return_only_integer([10, &quot;121&quot;, 56, 20, &quot;car&quot;, 3, &quot;lion&quot;]) ➞ [10, 56, 20,
3]<br>
return_only_integer([&quot;String&quot;, True, 3.3, 1]) ➞ [1]

In [6]:
def return_only_integer(ls):
  new_ls = []
  for i in ls:
    if str(i).isnumeric():
      if type(i)==int:
        new_ls.append(i)
  return new_ls

print(return_only_integer([9, 2, "space", "car", "lion", 16]))
print(return_only_integer(["hello", 81, "basketball", 123, "fox"]))
print(return_only_integer([10, "121", 56, 20, "car", 3, "lion"]))
print(return_only_integer(["String", True, 3.3, 1]))

[9, 2, 16]
[81, 123]
[10, 56, 20, 3]
[1]